#ifndef __Symbolics_H_
#define __Symbolics_H_

#include "Symbol.h"
#include "Int.h"
#include "Real.h"
#include "Zero.h"
#include "Eye.h"
#include "Bool.h"
#include "Error.h"
#include "Matrix.h"
#include "SymmetricMatrix.h"

#include "Abs.h"
#include "Acos.h"
#include "Add.h"
#include "Asin.h"
#include "Atan.h"
#include "Atan2.h"
#include "Cos.h"
#include "Der.h"
#include "Element.h"
#include "Equal.h"
#include "Greater.h"
#include "If.h"
#include "Inverse.h"
#include "Jacobian.h"
#include "Less.h"
#include "Mul.h"
#include "Neg.h"
#include "Pow.h"
#include "Scalar.h"
#include "Sign.h"
#include "Sin.h"
#include "Skew.h"
#include "Solve.h"
#include "Util.h"
#include "Tan.h"
#include "Transpose.h"
#include "Unknown.h"
#include "Outer.h"

#endif // __Symbolics_H_